### ISSUE TITLE
Issue while implementing single-core soc on esp 

### ISSUE THREAD

**Issue by mayank-kabra2001** [sld-columbia/esp#144]
I am receiving error while doing rtl simulation using {make xmsim}. 

![WhatsApp Image 2022-02-14 at 12 11 32 PM](https://user-images.githubusercontent.com/57330493/153814036-38ea7c56-68d9-43d3-9abe-f62549ce6ef0.jpeg)

I have used the following configuration - 
![image](https://user-images.githubusercontent.com/57330493/153814133-fff5dc31-ffdf-4c06-8e1f-02aed5e674b4.png)

Can someone help me out!!

**Comment by jzuckerman** [comment]
Hello, I just pushed a fix for this to the master branch. For Xcelium, you'll also need to apply a patch to the Ariane core as indicated here: https://esp.cs.columbia.edu/docs/setup/setup-guide/#patching-ariane-for-xcelium-simulator .

**Comment by harshitaaaaaa** [comment]
Yes, I have applied this patch but I am still facing the issue. I downloaded the patch mentioned in the link ([here](https://esp.cs.columbia.edu/docs/setup/xcelium_ariane.patch))

**Comment by mayank-kabra2001** [comment]
Yes, I have applied this patch but I am still facing the issue. I downloaded the patch mentioned in the link ([here](https://esp.cs.columbia.edu/docs/setup/xcelium_ariane.patch))
